services:
  node-mongoose:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: node-mongoose
    environment:
      - DB_URI=${DB_URI}
    develop:
      watch:
        - path: ./back/
          target: /app/
          action: sync
        - path: ./back/package.json
          action: rebuild
    ports:
      - 8080:8080
  react-app:
    build:
      context: ./front/
      dockerfile: Dockerfile
    container_name: react-app
    develop:
      watch:
        - path: ./front/
          target: /src/
          action: sync
        - path: ./front/package.json
          action: rebuild
    ports:
      - 3000:3000
    depends_on:
      - node-mongoose
    extra_hosts:
      - "local.voyage-stoique=127.0.0.1"
volumes:
  db_data:
