name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
      - 'back/**'
      - '**'
      - 'submodules/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH Agent
        run: ssh-add -l || echo "No SSH keys loaded"

      - name: Add DigitalOcean host to known_hosts
        run: |
          ssh-keyscan 209.38.227.24 >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        run: |
          ssh root@209.38.227.24 << 'EOF'
            set -e
            cd Voyage_Stoique/
            git reset --hard HEAD || echo "No changes to reset"
            git pull origin main
            git submodule update --remote --merge
            docker compose down
            docker compose build
            docker compose up -d
            docker compose logs --tail 100
            docker builder prune --filter "until=24h"
          EOF